<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Message_ErrorLogin</name>
   <tag></tag>
   <elementGuidId>936f68f3-d243-417f-8ab0-f81e7149c9a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[1]/div/div/form/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ff5c6868-eea0-45dc-9c71-3d0a8335fc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1687233686867</value>
      <webElementGuid>0119ecd8-2524-4df6-83e5-ee17bde0c6ac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
