<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_TitleProduct</name>
   <tag></tag>
   <elementGuidId>372c0a88-9f3d-4e5d-944e-ecd6b9b799e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div[2]/div/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>1ea7562f-41c7-422b-bf43-f1a7c3bd15eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1687233322944</value>
      <webElementGuid>99d7b2e3-24a6-40d9-97dd-33bcdb5188c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
