<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InventorySideBarLink</name>
   <tag></tag>
   <elementGuidId>101f4741-3f2f-43dc-8263-9a8ab4fc2a57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;inventory_sidebar_link&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d192bb2d-4216-4264-aa77-1ec64bd66af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1687244473645</value>
      <webElementGuid>08e98945-8143-42bd-aeba-404e71487633</webElementGuid>
   </webElementProperties>
</WebElementEntity>
